# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='商品上架时间')),
                ('desc', models.TextField(verbose_name='商品描述')),
                ('stock', models.IntegerField(verbose_name='商品数量')),
                ('count', models.IntegerField(default=0, verbose_name='商品销量')),
                ('commentCount', models.IntegerField(default=0, verbose_name='商品累计评论数')),
                ('goodSize', models.CharField(max_length=50, verbose_name='商品尺寸/大小/')),
                ('goodsStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='商品所属店铺')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(default='static/images/goods/default.jpg', upload_to='static/images/goods', verbose_name='商品图片')),
                ('status', models.BooleanField(default=False, verbose_name='是否默认显示')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='商品图片描述')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='所属商品 ')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='商品类型名称')),
                ('logo', models.ImageField(default='static/images/logo/goods-style1.png', upload_to='static/images/logo', verbose_name='商品类型图标')),
                ('intro', models.TextField(verbose_name='商品类别描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='父级类型')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType', verbose_name='商品类型'),
        ),
    ]
