# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=100, verbose_name='收货人')),
                ('recv_tel', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('country', models.CharField(default='中国', max_length=255)),
                ('province', models.CharField(max_length=100, verbose_name='收货人省份')),
                ('city', models.CharField(max_length=100, verbose_name='收货人城市')),
                ('area', models.CharField(max_length=50, verbose_name='收货人县/区/')),
                ('street', models.CharField(max_length=50, verbose_name='收货人街道')),
                ('desc', models.CharField(max_length=255, verbose_name='收货人详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认地址')),
            ],
        ),
        migrations.CreateModel(
            name='ParentAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.ParentAddress', verbose_name='父级地址')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.ParentAddress', verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='地址所属'),
        ),
    ]
