# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addr',
        ),
    ]
