# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加商品时间'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='number',
            field=models.IntegerField(default=0, verbose_name='购买商品数量'),
        ),
    ]
